site_name: app
site_description: Chicken Prices
repo_url: https://github.com/cigani/app
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/cigani">cigani</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
